"""empty message

Revision ID: 36f96efbb0dc
Revises: 0b738708d53e
Create Date: 2019-12-23 11:03:44.059441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36f96efbb0dc'
down_revision = '0b738708d53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user_profile', sa.Column('mobile_num', sa.String(length=11), nullable=True))
    op.drop_column('ihome_user_profile', 'mobile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user_profile', sa.Column('mobile', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('ihome_user_profile', 'mobile_num')
    # ### end Alembic commands ###
