"""empty message

Revision ID: bef8a6ace726
Revises: d83f20c98dcd
Create Date: 2020-01-09 15:41:01.989965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef8a6ace726'
down_revision = 'd83f20c98dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_order_info', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_order_info', 'trade_no')
    # ### end Alembic commands ###
