"""empty message

Revision ID: f4567bc5b79e
Revises: f7c1237ccb25
Create Date: 2019-12-22 11:50:12.374166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4567bc5b79e'
down_revision = 'f7c1237ccb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ihome_user_profile', sa.Column('mobile', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ihome_user_profile', 'mobile')
    # ### end Alembic commands ###
